name: Test Increment Workflow

permissions:
  contents: write

on: workflow_dispatch

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          script: |
            file = github.rest.repos.getContent({
              owner: "jbergles",
              repo: "number-goes-up",
              path: "number.txt"
            })
            sha = file.sha
            github.rest.repos.createOrUpdateFileContents({
              owner: "jbergles",
              repo: "number-goes-up",
              path: "number.txt",
              sha: sha,
              message: "doing an API commit",
              content: btoa(Math.floor((new Date()).getTime() / 1000).toString())
            })
