name: Test Increment Workflow

permissions:
  contents: write

on: workflow_dispatch

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createOrUpdateFileContents({
              owner: "jbergles",
              repo: "number-goes-up",
              path: "number.txt",
              mesasge: "doing an API commit",
              content: btoa("This is a test")
            })
